language: node_js
node_js:
  - '18'
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm install -g yarn
  - npm config set spin false
  - npm install -g npm@^8.19.4
script:
  - yarn test-ci
  - yarn build
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "jVHKBcZgRjHF/WO4+Btkrw5Sxeo5aTQioWXe7C/vgsPS43ISmMOLs1PmGdYLwDbKI6ub7Bjy0IIUHaqndz4qHRqZNzvgFTIXlHbLBzC2ZNY6K3Tm8H7dpzFAsvX5zVqShYRSv9lt3ebtdhpdxWTJHi5a67dVusa2dgfibO8I0X1HMXEDXNwzo8Kfl6k5XlHBxHJgnL76K6ZPu4YUK4gukjSnZLTWkcczaioYuuqEFQ39Q0kAAU4NTH0ECMXLlmg4Lrv3RS4Im2Lap0tm5meEPqm7foIJM5BI53t4CmMMbm7CGWrjtMZv0VYPctvh2RWBlm5sI07mWvUYS8Dg7ZtOITlh2k4lvdbW+0XNSG6HLoHAIpp7Cud8FbKPkroNyuEsLEdEyrOgDV/t0OhMslAsgDkCUZZUdDyyfLl2epfeHqWbS2Cir+h8J9kBayLyjL9VQhXiS/owWPAude0KZkWkF8mQ65itvKVr2KBVaIujRPWEE7+kKXcR9t6ocyx3jQEj/XqpB4RzjQIRsmmYKBWBptA7J6b4UMKpwGgrUSUrTEuA/nUZDu93nWHg4AvSRiGAJLmVkiGwSwVLAfPX7zbYh9bsfCRoC2I4WOSKfUcE2W8idXZga2bYQZVcnsqe0k7IfXbocn6oAmX0n4SSXaYGsXK546L7nyHm6nCF9q/noKE="
  file:
    - build/_output/flash-cards.wigt
    - build/_output/flash-cards-build-info.yml
  on:
    tags: true
    repo: ucfopen/flash-cards-materia-widget
notifications:
  email: false
  slack:
    secure: "BkqR8W6Y9xeIBL/DKGT5XgpiPKDtJinSAZA1bfyMg8whhbB0zuVahU/98wIwWLUssyENezZC+Hl2GwomQvpIDBENkRyM7B+Y3NZs8J0P3wfxCZMLigfmstu3lF4nWsy63ByRa+HW9pFgqRZzkWiP0Vvrk1s94NG6Y30g6xMCnzk0PMWGSgOlR475J38zIVL1UfWv1wOLtDCbD+rZJMtDUDOWEmiDTGiaHq+7pd4d3R0cnjUAQPtY/iuTEXiopWkRZAPOaF2pqLAKFN05tv71pudDQ4vXqFug9pSqwy0iv48cJ6IjCf834rC8oCovw34U06M1BTY1heUWhusNXWoih/C1XS/j4czz8FQ2EV4YvL8VERRi/EhyLZOcp3IfxfTDUCIWEXyfIW25CX5+JKw6/XKlXb5P8bbbgEHdpkbqKhXDiImyBYD30BCmrg3tl/AM7HLdOkHBoUPYk48j9T0uL0QBtk35qBGXI4N0YtXX1CQp4sIlRNEI+MwrqVd3y4AN5ATGPI7p8qCRVuSVYkLZnkb2tOrEp98DvqZNlp1fuQHs5mji7e7tLIri+5tT5Say7e5IsQvDJkW+WcUO2IzBP8e9IZ/vf/vThEGlXwqBEfocic8HyZO1FWtIM6o+k1lc4mBhoU3InRRKe1T+ThInt3OIrCP44NYxn4DYI0svemk="

